[project]
name = "audio-mangler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "ruff>=0.13.0",
    "scipy>=1.16.1",
]

[tool.uv.workspace]
members = [
    "audio-mangler",
]
